server:
  port: 9000
spring:
  application:
    name: spring-oauth2-authorization-server
  security:
    user:
      name: user
      password: password
      roles:
        - USER
    oauth2:
      authorizationserver:
        client:
          clientone:
            registration:
              client-id: "clientone"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/clientone"
              scopes:
                - "user.read"
                - "user.write"
                - "openid"
            require-authorization-consent: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.security: trace
    root: INFO
    org.springframework.web: INFO
    org.springframework.security.oauth2: DEBUG