server:
  port: 9000
spring:
  application:
    name: spring-oauth2-authorization-server
  security:
    user:
      name: user
      password: password
      roles:
        - USER
    oauth2:
      authorizationserver:
        client:
          gateway:
            registration:
              client-id: "gateway"
              client-secret: "{noop}secret1"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:9091/login/oauth2/code/gateway"
              scopes:
                - "user.read"
                - "user.write"
                - "openid"
            require-authorization-consent: true
            token:
              access-token-time-to-live: 60s
          mvcclient:
            registration:
              client-id: "mvcclient"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/mvcclient"
              scopes:
                - "user.read"
                - "user.write"
                - "openid"
            require-authorization-consent: true
            token:
              access-token-time-to-live: 90s
          public-client:
            registration:
              client-id: "public-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://127.0.0.1:3000"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
            require-proof-key: true
            token:
              access-token-time-to-live: 1h

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.security: TRACE
    root: INFO
    org.springframework.web: INFO
    org.springframework.security.oauth2: TRACE